### ISSUE TITLE
Unraid - No logs from /var/log appear in app

### ISSUE THREAD

**Issue by Krillsson** [Krillsson/monitee-agent#186]
> Another question. 
> I don't see logs in Monitee-app on smartphone. Can I change default variable `/vat/log` for `/mnt/user/Syslog`? 

 _Originally posted by @PrzemekSkw in [#185](https://github.com/Krillsson/monitee-agent/issues/185#issuecomment-2669428526)_

This is because you also need to uncomment line 38 in configuration.yml (so it looks like below)

```yaml
logReader:
  files: [ ]
  directories:
  # - data # sys-API data directory. You can enable log to file in application.properties
   - /var/log # Linux log directory
```

The reason its commented out is because this directory only exist in Linux, not in Windows and Mac

**Comment by PrzemekSkw** [comment]
Hello,
I uncomment like that but still have `0 files  0B` in Logs widget in App. Nothing happen when I click that field.
Regards.

**Comment by Krillsson** [comment]
Forgot to mention. Did you restart the container?

**Comment by PrzemekSkw** [comment]
Yes, I always stop container when I edit config files. I start it after and restart second time. Maybe it's because there's very large logs?

**Comment by Krillsson** [comment]
Now I'm puzzled. So if you do 

ls /var/log

From the unRAID terminal. Are there files?

And if you then use the command line from inside the container and do the same thing. Are the same files there?

**Comment by PrzemekSkw** [comment]
> Now I'm puzzled. So if you do
> 
> ls /var/log
> 
> From the unRAID terminal. Are there files?
```
root@unRAID:~# ls /var/log
apcupsd.events    btmp     dmesg       lastlog   nfsd/      plugins/           removed_uninstall_scripts@  spooler   unraid-api/
apcupsd.events.1  btmp.1   docker.log  libvirt/  nginx/     preclear/          samba/                      swtpm/    vfio-pci
apcupsd.events.2  cron     faillog     maillog   packages@  pwfail/            scripts@                    syslog    vfio-pci-errors
apcupsd.events.3  debug    gitcount    mcelog    phplog     removed_packages@  secure                      syslog.1  wg-quick.log
apcupsd.events.4  dhcplog  gitflash    messages  pkgtools/  removed_scripts@   setup@                      syslog.2  wtmp
```
> 
> And if you then use the command line from inside the container and do the same thing. Are the same files there?
From Monitee-agent container console:
```
# ls /var/log
apcupsd.events    apcupsd.events.4  debug       faillog   libvirt   nfsd      pkgtools  removed_packages           scripts  swtpm     unraid-api       wtmp
apcupsd.events.1  btmp              dhcplog     gitcount  maillog   nginx     plugins   removed_scripts            secure   syslog    vfio-pci
apcupsd.events.2  btmp.1            dmesg       gitflash  mcelog    packages  preclear  removed_uninstall_scripts  setup    syslog.1  vfio-pci-errors
apcupsd.events.3  cron              docker.log  lastlog   messages  phplog    pwfail    samba                      spooler  syslog.2  wg-quick.log
# 
```

**Comment by PrzemekSkw** [comment]
I can show my configs to bee sure I don't have any errors:

![Image](https://github.com/user-attachments/assets/556e00a0-1223-4f8b-9ac1-fb71f7f11dc0)

![Image](https://github.com/user-attachments/assets/4634f427-54b2-42d0-867c-73223f551f6c)

configuration.yml
```
linux:
  journalLogs:
    enabled: true
  systemDaemonServiceManagement:
    enabled: true
logReader:
  files: [ ]
  directories:
  # - data # sys-API data directory. You can enable log to file in application.properties
   - /var/log # Linux log directory
# web interface for running queries
```
